[env:native]
platform = native
test_framework = googletest
build_flags =
	-std=gnu++17
	-I src
lib_deps =
    google/googletest@^1.12.1

[env:esp32s3_n16r8]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
build_flags =
	-DBOARD_HAS_PSRAM
	-std=gnu++17
build_unflags =
	-std=gnu++11
; Tell PIO to compile the example file as the main program for this test
build_src_filter = +<../src/StateMachine.cpp>
